Bootstrap: docker
From: ubuntu:22.04

%post
    apt update && apt -y upgrade
    apt-get install -y build-essential
    apt-get install -y \
        wget \
        git \
        python3 \
        python3-pip \
        python3-virtualenv

    apt update && apt upgrade && apt install midori
    apt -y install firefox imagemagick
    apt-get install -y x11-apps gedit gimp evince nano
    apt-get install -y ghostscript

    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb
    dpkg -i cuda-keyring_1.0-1_all.deb
    apt-get update
    apt-get -y install cuda pciutils

#     wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
#     chmod +x Miniconda3-latest-Linux-x86_64.sh
#     bash Miniconda3-latest-Linux-x86_64.sh -b -p /usr/local/miniconda
# 
#     . /usr/local/miniconda/etc/profile.d/conda.sh
#     conda create --name sdwebui python=3.10.6 -y
#     conda activate sdwebui
# 
#     cd /usr/local
#     git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git
#     wget https://huggingface.co/andite/anything-v4.0/blob/main/anything-v4.5-pruned.ckpt -P your-model-path
#     mv your-model-path/anything-v4.5-pruned.ckpt stable-diffusion-webui/models/Stable-diffusion/
# 
#     pip3 install fastapi
#     pip3 install packaging
#     # pip3 install torch

# %runscript
#     . /usr/local/miniconda/etc/profile.d/conda.sh
#     conda activate sdwebui
#     cd /usr/local/stable-diffusion-webui
#     python3 webui.py
